# Generated by Django 2.0.3 on 2020-04-27 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('base', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ToppingPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_num', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.FoodType')),
            ],
        ),
        migrations.AddField(
            model_name='foodtype',
            name='size',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='orders.Size'),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='baseprice',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.FoodType'),
        ),
        migrations.AddField(
            model_name='baseprice',
            name='size',
            field=models.ManyToManyField(blank=True, to='orders.Topping'),
        ),
    ]
