# Generated by Django 2.0.3 on 2020-04-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseprice',
            name='size',
        ),
        migrations.RemoveField(
            model_name='foodtype',
            name='size',
        ),
        migrations.AddField(
            model_name='foodtype',
            name='size',
            field=models.ManyToManyField(to='orders.Size'),
        ),
    ]
