# Generated by Django 2.0.3 on 2020-04-27 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_baseprice_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseprice',
            name='size',
        ),
    ]
