# Generated by Django 2.0.3 on 2020-04-27 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_baseprice_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseprice',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.Size'),
        ),
    ]
