# Generated by Django 2.0.3 on 2020-04-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_baseprice_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
