# Generated by Django 2.0.3 on 2020-04-27 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200427_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppingprice',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.Size'),
        ),
        migrations.AlterField(
            model_name='toppingprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
