# Generated by Django 2.0.3 on 2020-04-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200427_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='base',
            field=models.CharField(max_length=30),
        ),
    ]
