# Generated by Django 2.0.3 on 2020-04-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200427_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='size',
            field=models.ManyToManyField(blank=True, to='orders.Size'),
        ),
    ]
