# Generated by Django 2.0.3 on 2020-05-28 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0013_auto_20200427_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.BasePrice')),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.FoodType')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Size')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Topping')),
                ('topping_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ToppingPrice')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
