# Generated by Django 2.0.3 on 2020-05-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='topping',
        ),
        migrations.AddField(
            model_name='order',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='orders.Topping'),
        ),
    ]
