# Generated by Django 2.0.3 on 2020-06-10 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200528_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprice',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_price', to='orders.FoodType'),
        ),
        migrations.AlterField(
            model_name='toppingprice',
            name='food',
            field=models.ManyToManyField(related_name='topping_price', to='orders.FoodType'),
        ),
    ]
