# Generated by Django 2.0.3 on 2020-06-18 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20200614_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='username',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
