# Generated by Django 2.0.3 on 2020-06-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_shoppingcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='orders',
            field=models.ManyToManyField(related_name='orders', to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='status',
            field=models.CharField(choices=[('1', 'unconfirmed'), ('2', 'pending'), ('3', 'complete')], default='1', max_length=20),
        ),
    ]
