# Generated by Django 2.0.3 on 2020-06-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20200618_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='orders',
            field=models.ManyToManyField(to='orders.Order'),
        ),
    ]
