# Generated by Django 2.0.3 on 2020-06-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20200619_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='orders',
            field=models.ManyToManyField(related_name='orders', to='orders.Order'),
        ),
    ]
